### ISSUE TITLE
ini files should be fully managed (ie. purge => true)

### ISSUE THREAD

**Issue by helge000** [choria-io/mcollective-choria#287] opened 2017-06-12 13:43 UTC
Currently, ini settings are set using [ini_settings](https://github.com/choria-io/puppet-mcollective/blob/master/manifests/module_plugin.pp#L100)

- At least, this does not allow us reverting from fixed puppet and middleware hosts to SRV records in choria.cfg.
- There are many instances with with non - standard settings which can result in a noop config.

**Comment by ripienaar** [comment] 2017-06-12 13:46
Dupe of https://github.com/choria-io/puppet-mcollective/issues/46 and https://github.com/choria-io/puppet-mcollective/issues/45

**Closed by ripienaar** 2017-06-12 13:46 UTC
